# Generated by Django 4.1.6 on 2023-10-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_portfolio', '0002_alter_gallary_options_abouts_use_brands_use_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='use',
            field=models.BooleanField(default=True),
        ),
    ]
